# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import remote_snake_pb2 as remote__snake__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in remote_snake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteSnakeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetId = channel.unary_unary(
                '/snake_sim.RemoteSnake/SetId',
                request_serializer=remote__snake__pb2.SnakeId.SerializeToString,
                response_deserializer=remote__snake__pb2.Empty.FromString,
                _registered_method=True)
        self.SetStartLength = channel.unary_unary(
                '/snake_sim.RemoteSnake/SetStartLength',
                request_serializer=remote__snake__pb2.StartLength.SerializeToString,
                response_deserializer=remote__snake__pb2.Empty.FromString,
                _registered_method=True)
        self.SetStartPosition = channel.unary_unary(
                '/snake_sim.RemoteSnake/SetStartPosition',
                request_serializer=remote__snake__pb2.StartPosition.SerializeToString,
                response_deserializer=remote__snake__pb2.Empty.FromString,
                _registered_method=True)
        self.SetInitData = channel.unary_unary(
                '/snake_sim.RemoteSnake/SetInitData',
                request_serializer=remote__snake__pb2.EnvInitData.SerializeToString,
                response_deserializer=remote__snake__pb2.Empty.FromString,
                _registered_method=True)
        self.Update = channel.stream_stream(
                '/snake_sim.RemoteSnake/Update',
                request_serializer=remote__snake__pb2.EnvData.SerializeToString,
                response_deserializer=remote__snake__pb2.UpdateResponse.FromString,
                _registered_method=True)


class RemoteSnakeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStartLength(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStartPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInitData(self, request, context):
        """Updated SetInitData RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request_iterator, context):
        """Updated Update RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteSnakeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetId,
                    request_deserializer=remote__snake__pb2.SnakeId.FromString,
                    response_serializer=remote__snake__pb2.Empty.SerializeToString,
            ),
            'SetStartLength': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStartLength,
                    request_deserializer=remote__snake__pb2.StartLength.FromString,
                    response_serializer=remote__snake__pb2.Empty.SerializeToString,
            ),
            'SetStartPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStartPosition,
                    request_deserializer=remote__snake__pb2.StartPosition.FromString,
                    response_serializer=remote__snake__pb2.Empty.SerializeToString,
            ),
            'SetInitData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInitData,
                    request_deserializer=remote__snake__pb2.EnvInitData.FromString,
                    response_serializer=remote__snake__pb2.Empty.SerializeToString,
            ),
            'Update': grpc.stream_stream_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=remote__snake__pb2.EnvData.FromString,
                    response_serializer=remote__snake__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snake_sim.RemoteSnake', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snake_sim.RemoteSnake', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteSnake(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snake_sim.RemoteSnake/SetId',
            remote__snake__pb2.SnakeId.SerializeToString,
            remote__snake__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStartLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snake_sim.RemoteSnake/SetStartLength',
            remote__snake__pb2.StartLength.SerializeToString,
            remote__snake__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStartPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snake_sim.RemoteSnake/SetStartPosition',
            remote__snake__pb2.StartPosition.SerializeToString,
            remote__snake__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snake_sim.RemoteSnake/SetInitData',
            remote__snake__pb2.EnvInitData.SerializeToString,
            remote__snake__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/snake_sim.RemoteSnake/Update',
            remote__snake__pb2.EnvData.SerializeToString,
            remote__snake__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
